---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: bookservice-deployment-v2
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: bookservice
        version: "2"
    spec:
      containers:
      - name: bookservice
        image: honeycombio/bookservice-demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: VERSION
          value: "2"
        command: ["/go/bin/srv", "--mongo", "bookservice-mongodb"]
