# Modified from `helm install --name mongodb --set persistence.enabled=false stable/mongodb`
---
# Source: mongodb/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: bookservice-mongodb
  labels:
    app: bookservice-mongodb
    chart: "mongodb-0.4.7"
    release: "mongodb"
    heritage: "Tiller"
type: Opaque
data:
  mongodb-root-password: ""
  mongodb-password: ""

---
# Source: mongodb/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: bookservice-mongodb
  labels:
    app: bookservice-mongodb
    chart: "mongodb-0.4.7"
    release: "mongodb"
    heritage: "Tiller"
spec:
  ports:
  - name: mongodb
    port: 27017
    targetPort: mongodb
  selector:
    app: bookservice-mongodb

---
# Source: mongodb/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bookservice-mongodb
  labels:
    app: bookservice-mongodb
    chart: "mongodb-0.4.7"
    release: "mongodb"
    heritage: "Tiller"
spec:
  template:
    metadata:
      labels:
        app: bookservice-mongodb
    spec:
      containers:
      - name: bookservice-mongodb
        image: "bitnami/mongodb:3.4.2-r0"
        imagePullPolicy: ""
        env:
        - name: MONGODB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bookservice-mongodb
              key: mongodb-root-password
        - name: MONGODB_USERNAME
          value: ""
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bookservice-mongodb
              key: mongodb-password
        - name: MONGODB_DATABASE
          value: ""
        ports:
        - name: mongodb
          containerPort: 27017
        livenessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: data
          mountPath: /bitnami/mongodb
        resources:
          requests:
            cpu: 100m
            memory: 256Mi

      volumes:
      - name: data
        emptyDir: {}
