---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bookservice-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: bookservice
        version: "1"
    spec:
      containers:
      - name: bookservice
        image: honeycombio/bookservice-demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        command: ["/go/bin/srv", "--mongo", "bookservice-mongodb"]

---
apiVersion: v1
kind: Service
metadata:
  name: bookservice
  labels:
    app: bookservice
spec:
  ports:
  - name: http-bookservice  # Port name must start with http for istio injection to work properly
    port: 8080
    targetPort: 8080
  selector:
    app: bookservice
